### ISSUE TITLE
Create sentences containing addresses 

### ISSUE THREAD

**Issue by omri374** [omri374/address_detection#2]
(for example: I live in XYZ) with the presidio data generator (or some other tool)

**Comment by omri374** [comment]
Hi @fatemerhmi, depending on what you're after. I looked into reusing the presidio data generator for this purpose and it requires some refactoring, which I was planning to do in the next week or so. For general purpose data generation we could use [FakeNameGenerator(https://www.fakenamegenerator.com/), [faker](https://faker.readthedocs.io/en/master/) and/or [mimesis](https://mimesis.readthedocs.io/)

**Comment by fatemerhmi** [comment]
Hi @omri374, 
I was looking into how the presidio data generator uses a csv file and a text file (including templates) to generates a nice dataset. I was then searching if there are any other options that we want to explore before closing this issue. 

Maybe the annotation for creating templates can be part of this issue. :)
